#include<iostream>
using namespace std;
 main() {
	int num1;
	cout << "Number 1: ";
	cin >> num1;
	int num2;
	cout << "Number 2: ";
	cin >> num2;
	int num3;
	cout << "Number 3: ";
	cin >> num3;
	int num4;
	cout << "Number 4: ";
	cin >> num4;
	int num5;
	cout << "Number 5: ";
	cin >> num5;
	int num6;
	cout << "Number 6: ";
	cin >> num6;
	int num7;
	cout << "Number 7: ";
	cin >> num7;
	int num8;
	cout << "Number 8: ";
	cin >> num8;
	int num9;
	cout << "Number 9: ";
	cin >> num9;
	int num10;
	cout << "Number 10: ";
	cin >> num10;
	int num11;
	cout << "Number 11: ";
	cin >> num11;
	int num12;
	cout << "Number 12: ";
	cin >> num12;
	int num13;
	cout << "Number 13: ";
	cin >> num13;
	int num14;
	cout << "Number 14: ";
	cin >> num14;
	int num15;
	cout << "Number 15: ";
	cin >> num15;
	int addition = num1+num2+num3+num4+num5;
	int multiplication = num6*num7*num8*num9*num10;
	int subtraction = num11-num12-num13-num14-num15;
	int n1 = addition+multiplication;
	int final_result = n1-subtraction;
	cout << "The final result is: " << final_result << endl;
}
